import cardinality_properties_cardinal_functions_inequalities_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace cardinality_properties_cardinal_functions_inequalities_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end cardinality_properties_cardinal_functions_inequalities_canonical_lane_mathlib
end HautevilleHouse
